CREATE TABLE transTypeEnum (id INTEGER PRIMARY KEY AUTOINCREMENT, transType TEXT);
INSERT INTO transTypeEnum(transType) VALUES('BUY'), ('SELL');

CREATE TABLE transStatusEnum (id INTEGER PRIMARY KEY AUTOINCREMENT, transStatus TEXT);
INSERT INTO transStatusEnum(transStatus) VALUES('ACTIVE'), ('FULFILLED'), ('CANCELLED');


CREATE TABLE User (
	id SERIAL PRIMARY KEY,
	name VARCHAR(256),
	nickname VARCHAR(256) UNIQUE,
	password VARCHAR(256)
	
);

CREATE TABLE Order (
	id SERIAL PRIMARY KEY,
	type REFERENCES transTypeEnum(id) NOT NULL,
	status REFERENCES transStatusEnum(id) NOT NULL,
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	source INTEGER REFERENCES User(id),
	value DOUBLE NOT NULL DEFAULT 0,
	amount INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE Transaction (
	id INTEGER REFERENCES Order(id),
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	destination INTEGER REFERENCES User(id),
	value DOUBLE NOT NULL DEFAULT 0
);

CREATE TABLE Diginote (
	id SERIAL PRIMARY KEY,
	value int DEFAULT 1,
	owner INTEGER REFERENCES User(id)
);